### ISSUE TITLE
Update the csip.engr.colostate.edu service to use https

### ISSUE THREAD

**Issue by cschwinderg** [Eastern-Research-Group/lew#105]
**Change Agent Contact Information**
Brad

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
Update the https://csip.engr.colostate.edu:8088 service to use https instead of http.

**Comment by coobr01** [comment]
Done in v2.1.0
