### ISSUE TITLE
Prevent usage of url parameter in swagger documentation

### ISSUE THREAD

**Issue by cschwinderg** [Eastern-Research-Group/lew#106]
**Change Agent Contact Information**
Brad

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
Yes but its to correct a finding and not to introduce new functionality that would change the posture.

**Describe the change**
Users can append the url paramter (example below) which results in strange behavior. We should not allow the url parameter.

https://lew.epa.gov/api-docs/index.html?url=https://raw.githubusercontent.com/z9nsis/swagger/main/test.yaml
![xss-lew epa gov (002)](https://user-images.githubusercontent.com/46329268/177794734-69a81d04-60f8-449c-824e-6b9b6daa2b3b.png)

Also the sample swagger file should be removed. https://lew.epa.gov/api-docs/og_index.html

**Comment by coobr01** [comment]
Done in v2.1.0
