### ISSUE TITLE
WebLink Updates

### ISSUE THREAD

**Issue by cschwinderg** [Eastern-Research-Group/lew#112]
**Change Agent Contact Information**
Rachel Urban 

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
Update LEW using the following Word doc:

[LEW updates.docx](https://github.com/Eastern-Research-Group/lew/files/9373607/LEW.updates.docx)

**Comment by coobr01** [comment]
Please add EPA (pdf) postfix for the hyperlinks pointing directly to pdf files. I know we can't show the file size but we should at least put the pdf indicator.

**Comment by cschwinderg** [comment]
The (pdf) postfix has been added to the pdf hyperlinks.

**Comment by coobr01** [comment]
Update looks good, ty!
