### ISSUE TITLE
Bug in calculations for leap years

### ISSUE THREAD

**Issue by cschwinderg** [Eastern-Research-Group/lew#113]
**Change Agent Contact Information**
Rachel  Urban

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
LEW returns `UNKNOWN` when selecting 12/31 as the end date on a leap year. We need to update the code so that Feb 28th's data gets copied into Feb29th for leap years only. More details in the email chain below. 

![image](https://user-images.githubusercontent.com/46329268/185390574-70d9a541-68f0-4e5b-bf76-3f39d22a1127.png)

**Comment by cschwinderg** [comment]
## Full Email Chain

I think that approach sounds reasonable so yes, I agree with Caleb’s suggestion. Thanks.
______________________________
Rachel Urban  |  EPA/Office of Water/Stormwater Permits Team
1200 Pennsylvania Avenue, MC 4203M, Washington, DC 20460
[urban.rachel@epa.gov](mailto:urban.rachel@epa.gov)  |  202.564.2649

From: Brad Cooper <[Brad.Cooper@erg.com](mailto:Brad.Cooper@erg.com)> 
Sent: Tuesday, August 09, 2022 5:30 PM
To: Caleb Schwind <[caleb.schwind@erg.com](mailto:caleb.schwind@erg.com)>; Urban, Rachel <[Urban.Rachel@epa.gov](mailto:Urban.Rachel@epa.gov)>; Keith, Elinor <[Keith.Elinor@epa.gov](mailto:Keith.Elinor@epa.gov)>
Cc: Clipper, Christopher <[clipper.christopher@epa.gov](mailto:clipper.christopher@epa.gov)>; Schaner, Greg <[Schaner.Greg@epa.gov](mailto:Schaner.Greg@epa.gov)>; Skovira, Lindsay <[skovira.lindsay@epa.gov](mailto:skovira.lindsay@epa.gov)>
Subject: RE: Bug/Error - LEW - R factor calculation

EPA LEW Team, do you agree with Caleb’s suggestion below? If so, we’ll start working on this update as well as the update to the home page text/link sent last week.

Brad Cooper
Eastern Research Group, Inc.
[Brad.Cooper@erg.com](mailto:Brad.Cooper@erg.com)
703.633.1685 (w)
703.727.8015 (m)

   [www.erg.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.erg.com%2F&data=05%7C01%7Ccaleb.schwind%40erg.com%7C9506c16fbaf54e1ce2d808da7ac6c116%7Ca17e3fab8d2346f287f33fceb7c6a000%7C1%7C0%7C637957291322428988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jE8%2Bu3Zks2DBQrBfQHaathpIoInDrA3qJAlx%2FRgQDSk%3D&reserved=0)

From: Caleb Schwind <[Caleb.Schwind@erg.com](mailto:Caleb.Schwind@erg.com)> 
Sent: Tuesday, August 9, 2022 10:21 AM
To: Brad Cooper <[Brad.Cooper@erg.com](mailto:Brad.Cooper@erg.com)>; Urban, Rachel <[Urban.Rachel@epa.gov](mailto:Urban.Rachel@epa.gov)>; Keith, Elinor <[Keith.Elinor@epa.gov](mailto:Keith.Elinor@epa.gov)>
Cc: Clipper, Christopher <[clipper.christopher@epa.gov](mailto:clipper.christopher@epa.gov)>; Schaner, Greg <[Schaner.Greg@epa.gov](mailto:Schaner.Greg@epa.gov)>; Skovira, Lindsay <[skovira.lindsay@epa.gov](mailto:skovira.lindsay@epa.gov)>
Subject: RE: Bug/Error - LEW - R factor calculation

The issue is being caused by selecting 12/31 as the end date on a leap year. The CSIP service is only returning 365 days worth of data for leap years, and LEW is expecting to get back 366 days of data. 

The CO team says they treat all years as normal length years, so we will need to update the LEW code to work around this issue.

I suggest that for leap years, we duplicate the data for the last day in February. So, for a leap year, the value for February 29th will be the same value as February 28th. Does that sound like a good approach to working around this issue? 

Thank you,
Caleb Schwind
ERG
Jr. Software Developer, Charlottesville Office
[caleb.schwind@erg.com](mailto:caleb.schwind@erg.com)
Office          (434) 979-0218 ext. 14108
Direct Dial  (434) 979-0382
   [www.erg.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.erg.com%2F&data=05%7C01%7Ccaleb.schwind%40erg.com%7C9506c16fbaf54e1ce2d808da7ac6c116%7Ca17e3fab8d2346f287f33fceb7c6a000%7C1%7C0%7C637957291322584757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=515KQVwQpVpwYkZzwq10lnSfS%2FkbuPyFdDAq4Sh6BYg%3D&reserved=0)

From: Brad Cooper <[Brad.Cooper@erg.com](mailto:Brad.Cooper@erg.com)> 
Sent: Tuesday, August 9, 2022 8:51 AM
To: Urban, Rachel <[Urban.Rachel@epa.gov](mailto:Urban.Rachel@epa.gov)>; Keith, Elinor <[Keith.Elinor@epa.gov](mailto:Keith.Elinor@epa.gov)>
Cc: Clipper, Christopher <[clipper.christopher@epa.gov](mailto:clipper.christopher@epa.gov)>; Schaner, Greg <[Schaner.Greg@epa.gov](mailto:Schaner.Greg@epa.gov)>; Skovira, Lindsay <[skovira.lindsay@epa.gov](mailto:skovira.lindsay@epa.gov)>; Caleb Schwind <[Caleb.Schwind@erg.com](mailto:Caleb.Schwind@erg.com)>
Subject: RE: Bug/Error - LEW - R factor calculation

The ERG LEW will look into this, but we’ll likely need to contact the Colorado RULSE Team as the year (2024) for both the start and end dates are likely causing the issue. You can test this by selecting any location and using the 2024 year.

Thank you,
Brad Cooper
Eastern Research Group, Inc.
[Brad.Cooper@erg.com](mailto:Brad.Cooper@erg.com)
703.633.1685 (w)
703.727.8015 (m)

   [www.erg.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.erg.com%2F&data=05%7C01%7Ccaleb.schwind%40erg.com%7C9506c16fbaf54e1ce2d808da7ac6c116%7Ca17e3fab8d2346f287f33fceb7c6a000%7C1%7C0%7C637957291322584757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=515KQVwQpVpwYkZzwq10lnSfS%2FkbuPyFdDAq4Sh6BYg%3D&reserved=0)

From: Urban, Rachel <[Urban.Rachel@epa.gov](mailto:Urban.Rachel@epa.gov)> 
Sent: Tuesday, August 9, 2022 8:45 AM
To: Keith, Elinor <[Keith.Elinor@epa.gov](mailto:Keith.Elinor@epa.gov)>
Cc: Clipper, Christopher <[clipper.christopher@epa.gov](mailto:clipper.christopher@epa.gov)>; Schaner, Greg <[Schaner.Greg@epa.gov](mailto:Schaner.Greg@epa.gov)>; Skovira, Lindsay <[skovira.lindsay@epa.gov](mailto:skovira.lindsay@epa.gov)>; Brad Cooper <[Brad.Cooper@erg.com](mailto:Brad.Cooper@erg.com)>
Subject: FW: Bug/Error - LEW - R factor calculation

CAUTION: Don't open links or attachments unless you recognize the sender and know they are safe.
Good morning, Elinor.

We received an email alerting us to a possible issue with the LEW Calculator. Chris Clipper, whom we’ll soon inquire about changing to be the application owner for LEW, checked and received the same result. Chris said “I received the same result as described below when I entered the data from the screenshot (attached image file), so this is a bug. In the Calculation Results, the R Factor is shown as “Unknown” and the text that follows “A rainfall erosivity factor of less than 5.0 has been calculated for your site and period of construction.“” 

Please see the email below and the attachment for more details. Is someone able to look into this and help with any resolution that may be needed? I cc’ed Brad so he’s aware.

Thanks,
Rachel
______________________________
Rachel Urban  |  EPA/Office of Water/Stormwater Permits Team
1200 Pennsylvania Avenue, MC 4203M, Washington, DC 20460
[urban.rachel@epa.gov](mailto:urban.rachel@epa.gov)  |  202.564.2649

From: Randall Rettig <[RRettig@engeo.com](mailto:RRettig@engeo.com)> 
Sent: Tuesday, July 26, 2022 12:29 PM
To: CGP <[CGP@epa.gov](mailto:CGP@epa.gov)>
Subject: Possible R factor calculation error

Hello,

While using your Rainfall Erosivity Factor Calculator for Small Construction Sites today I noticed a possible computing error I wanted to bring to your attention. I have attached a screenshot of the possible error to this email. It gave me a value of “Unknown” when it did not seem like a valid answer. Let me know if you have any questions, thank you!

Sincerely,

Randall Rettig
Staff Water Resources Engineer

 

ENGEO Incorporated
320 Goddard Suite 100
Irvine, CA 92618
(949) 529-3479 Phone
(888) 279-2698 Fax 
[www.engeo.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.engeo.com%2F&data=05%7C01%7Ccaleb.schwind%40erg.com%7C9506c16fbaf54e1ce2d808da7ac6c116%7Ca17e3fab8d2346f287f33fceb7c6a000%7C1%7C0%7C637957291322584757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M%2FpmKS2IAm5oh3w6ORnHadAazOM8c256AfaBJDg4FVg%3D&reserved=0)
CONNECT WITH ENGEO:                
________________________________________

*******Due to the potential that information by electronic media can deteriorate, be damaged, lost or modified unintentionally or otherwise, use of this electronic data by anyone other than ENGEO Incorporated shall be at the sole risk of such user and without liability or legal exposure to ENGEO Incorporated. The recipient is responsible for verifying the accuracy of data against governing hard copy documentation. Recipient assumes all risks in the changing or modification of data and revisions or updating of hard copy documents.*********

**Comment by coobr01** [comment]
Thanks, looks good from my testing.
