### ISSUE TITLE
Update 3rd party dependencies

### ISSUE THREAD

**Issue by cschwinderg** [Eastern-Research-Group/lew#114]
**Change Agent Contact Information**
Caleb

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
Update the 3rd party dependencies.

**Comment by coobr01** [comment]
Dang that looks good!

![image](https://user-images.githubusercontent.com/1842830/185616843-e6ad0e28-fe47-4728-9719-b9ab593af43d.png)
