### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by cschwinderg** [Eastern-Research-Group/lew#137]
**Change Agent Contact Information**
Christopher Clipper

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
- [x] ~In the “SHARE” section for social media some things need to be updated for “formerly Twitter, now known as X …” including the logo, hover text and maybe the website.~
- [x] Also in “SHARE” I recommend removing the envelope email function since “CONTACT US” with email functionality is directly above it. It’s confusing with both of them.
- [x] Move “For questions or comments, email EPA’s CGP staff at [cgp@epa.gov](mailto:cgp@epa.gov).” to the bottom of the page under the “Calculate R Factor” button.
- [x] Above the number 1 include the title “Steps to Calculate an R Factor for your Small Construction Project”
- [x] Above “EPA’s stormwater regulations allow …” include a title like “Background” or “Introduction”. Whatever aligns with the EPA web standards.
- [x] Change the text in number 1 to “Select the estimated start and end dates of construction by clicking the calendar icons below and using the dropdown calendar. The period of construction activity begins at initial earth disturbance and ends with final stabilization.” Put this text together in one shaded area and remove the second shaded area.
- [x] Change the text in number 2 to “Locate your small construction project by entering the address in the search box or by clicking on the map.
- [x] Change the text in number 3 to “Click the “Calculate R Factor” button below.”

**Comment by coobr01** [comment]
Thank you, closing out this old already implemented change request.
