### ISSUE TITLE
Leap year check / validation

### ISSUE THREAD

**Issue by coobr01** [Eastern-Research-Group/lew#20]
While most of the date handling code was migrated as-is from the legacy application, just based on some other issues encountered, it would be prudent to test using leap years at some point.

**Comment by renaemyers** [comment]
From: Jack Carlson <pspicata@rams.colostate.edu> 
Sent: Monday, February 3, 2020 3:55 PM
To: Renae Myers <Renae.Myers@erg.com>
Cc: Olaf David <odavid@rams.colostate.edu>
Subject: Re: Question about RUSLE2 service

Renae,

It would seem acceptable logic to start at the project start day of year (DOY) and sum the EI_DAILY_AMOUNT values for the duration of the project (assuming R is a simple sum of daily values).  If project duration straddles December 31, 2020 (DOY 366)  and has, for example, 15 days remaining in the duration, then the EI_DAILY_AMOUNT values for the first 15 days are included in the calculation.  

There is no leap year table of EI_DAILY_AMOUNT values to my knowledge.  

Jack R. Carlson
Senior Research Associate
Department of Civil and Environmental Engineering
Colorado State University
Fort Collins, Colorado

On Feb 3, 2020, at 11:12 AM, Renae Myers <Renae.Myers@erg.com> wrote:

Hello,
 
I am an EPA contractor supporting the Low Erosivity Waiver Erosion Factor Calculator. I have a question about our use of the service athttp://csip.engr.colostate.edu/r2/epa/climates/: there are 365 values returned for EI_DAILY_AMOUNT, which we map to days of the year, then apply those that fall into a project time range to calculate an R factor. Can you advise how we should handle leap years when using this data?
 
Thank you,
Renae Myers
Eastern Research Group, Inc.
(443) 983-7700 | renae.myers@erg.com

**Comment by renaemyers** [comment]
The new R Factor calculation is performed as described above in the email from Jack Carlson.
