### ISSUE TITLE
Work around 301 HTTP status code for /api-docs

### ISSUE THREAD

**Issue by coobr01** [Eastern-Research-Group/lew#53]
**Change Agent Contact Information**
Brad Cooper

**Is this an emergency change request?**
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
No

**Describe the change**
In the Cloud.gov log files I see a 301 when users navigate to the /api-docs page. My guess, its a redirect from the root to the actual api home page. Let's see if we can work around that somehow to help unclutter the log files.

**Additional context**
N/A

**Comment by cschwinderg** [comment]
@coobr01 Can you share the log files?
