### ISSUE TITLE
Make sure the EL value does not exceed 100%

### ISSUE THREAD

**Issue by coobr01** [Eastern-Research-Group/lew#61]
**Change Agent Contact Information**
Capture as much information about the submitter as possible {Name, email, telephone, submission date/time, etc.}.

Development team based on review of 
[fact3-1.pdf](https://github.com/Eastern-Research-Group/lew/files/4142049/fact3-1.pdf)

**Is this an emergency change request?**

No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**

No

**Describe the change**

The maximum EI value should not exceed 100% for projects that are one year or longer (meaning that the R factor for a project should not exceed 100% of the annual R factor).

**Comment by renaemyers** [comment]
All projects spanning 365 days or longer now are assigned an R Factor of 100% of the annual EI value.
