### ISSUE TITLE
Update CONTACT US link from ONE EPA Template

### ISSUE THREAD

**Issue by coobr01** [Eastern-Research-Group/lew#62]
**Change Agent Contact Information**
Capture as much information about the submitter as possible {Name, email, telephone, submission date/time, etc.}.

Hui Zhou

**Is this an emergency change request?**

No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**

No

**Describe the change**
Provide a clear and concise description of the change. Include information about how to reproduce any issue(s) including any software version(s) and device make/model(s) used.

We need to update the contact us location to be lew specific.

**Comment by renaemyers** [comment]
Updated the CONTACT US link to a mailto cgp@epa.gov.
![image](https://user-images.githubusercontent.com/17788195/76788441-4ee87f00-6791-11ea-8b72-5e5fcd19c7b4.png)
