### ISSUE TITLE
Move jshint dependency to dev dependencies

### ISSUE THREAD

**Issue by renaemyers** [Eastern-Research-Group/lew#65]
**Change Agent Contact Information**
Capture as much information about the submitter as possible {Name, email, telephone, submission date/time, etc.}.

Brad Cooper
brad.cooper@erg.com

**Is this an emergency change request?**
Yes/No
No

**Does the request impact the security posture of the application/system? Please note, if so, the application's ISSO will need to be involved. The current application ISSO is listed in the CMP.**
Yes/No
No

**Describe the change**
Provide a clear and concise description of the change. Include information about how to reproduce any issue(s) including any software version(s) and device make/model(s) used.

In package.json, move jshint from dependencies to devDependencies.

**Additional context**
Add  other context or screenshots about the change request here.
![image](https://user-images.githubusercontent.com/17788195/76794696-f2d82780-679d-11ea-8b09-e026c295571f.png)

**Comment by coobr01** [comment]
done.
